# Generated by Django 3.2.16 on 2023-11-07 21:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StandaardExterneOmschrijving",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("titel", models.CharField(max_length=100, unique=True)),
                ("tekst", models.CharField(max_length=2000, unique=True)),
            ],
            options={
                "verbose_name": "Standaard externe omschrijving",
                "verbose_name_plural": "Standaard externe omschrijvingen",
            },
        ),
    ]
