# Generated by Django 3.2.16 on 2023-11-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standaardexterneomschrijving",
            name="tekst",
            field=models.CharField(max_length=2000),
        ),
    ]
