# Generated by Django 3.2.16 on 2024-01-24 12:13

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_standaardexterneomschrijving_tekst"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaaktypeCategorie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=100, unique=True)),
                ("taaktypes", utils.fields.ListJSONField(default=list)),
            ],
        ),
    ]
