# Generated by Django 4.2.15 on 2025-06-05 19:42

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_standaardexterneomschrijving_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeldingAfhandelreden",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                (
                    "reden",
                    models.CharField(
                        choices=[
                            ("reeds_ingepland", "Reeds ingepland"),
                            ("niet_nu", "Niet nu"),
                            ("Niet voor ons", "Niet voor ons"),
                            ("doen_we_niet", "Doen we niet"),
                            ("onduidelijk", "Onduidelijk"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "specificatie_opties",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="standaardexterneomschrijving",
            name="specificatie_opties",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="standaardexterneomschrijving",
            name="zichtbaarheid",
            field=models.CharField(
                choices=[
                    ("altijd", "Altijd tonen"),
                    ("opgelost", "Alleen tonen bij opgelost"),
                    ("niet_opgelost", "Alleen tonen bij niet opgelost"),
                    ("verbergen", "Verbergen"),
                ],
                default="altijd",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="standaardexterneomschrijving",
            name="reden",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standaard_externe_omschrijvingen_voor_melding_afhandelreden",
                to="main.meldingafhandelreden",
            ),
        ),
    ]
