# Generated by Django 4.2.15 on 2025-06-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_meldingafhandelreden_reden_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meldingafhandelreden",
            name="toelichting",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
