# Generated by Django 4.2.15 on 2025-12-19 11:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_meldingafhandelreden_toelichting"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomatRSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            (
                                "melding_afhandelen_door_taak",
                                "Melding afhandelen door taak",
                            ),
                            (
                                "taak_aanmaken_bij_onderwerp",
                                "Taak aanmaken door onderwerp",
                            ),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("settings", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
