# Generated by Django 5.2.10 on 2026-06-05 07:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_automatrsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('aangepast_op', models.DateTimeField(auto_now=True)),
                ('batch_uuid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('melding_uuid', models.CharField(max_length=36)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('send_after', models.DateTimeField()),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('sending', 'Bezig met versturen'), ('sent', 'Verstuurd'), ('cancelled', 'Geannuleerd'), ('error', 'Fout')], default='staged', max_length=20)),
                ('taken', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        )
    ]
