version: '3'
services:
  gateway:
    container_name: regie.mor.local
    build: ./nginx
    volumes:
      - ./nginx/nginx-default.development.conf:/etc/nginx/conf.d/default.conf
      - ./media:/media
    depends_on:
      regie_app:
        condition: service_started
    ports:
      - 8003:8003
    networks:
      mor_bridge_network:
    env_file:
      - .env.local
  regie_app:
    build: ./app
    env_file:
      - .env.local
    volumes:
      - ./media:/media
      - ./app:/app
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_started
    networks:
      - regie_network
      - mor_bridge_network
    command: ["bash", "/app/deploy/docker-entrypoint.development.sh"]

  redis:
    image: redis
    networks:
      - regie_network
    ports:
      - "6379"

  database:
    image: postgis/postgis:11-3.3
    shm_size: '1024m'
    ports:
      - "7997:5432"
    env_file:
      - .env.local
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - regie_network

volumes:
  postgres-data:

networks:
  regie_network:
    external: true
  mor_bridge_network:
    external: true
