version: '3'
services:
  app:
    build: ./app
    ports:
      - "8003:8000"
    env_file:
      - .env.test
    volumes:
      - ./app:/app
    depends_on:
      database:
        condition: service_healthy
    networks:
      - regie_network

  redis:
    image: redis
    networks:
      - regie_network
    ports:
      - "6379"

  database:
    image: postgis/postgis:11-3.3
    shm_size: '1024m'
    ports:
      - "5432"
    env_file:
      - .env.test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - regie_network

networks:
  regie_network:
    external: true
