# Generated by Django 3.2.16 on 2024-07-01 13:53

import uuid

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instelling",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                (
                    "mor_core_basis_url",
                    models.URLField(default="http://core.mor.local:8002"),
                ),
                ("mor_core_gebruiker_email", models.EmailField(max_length=254)),
                (
                    "mor_core_gebruiker_wachtwoord",
                    encrypted_model_fields.fields.EncryptedCharField(),
                ),
                ("mor_core_token_timeout", models.PositiveIntegerField(default=0)),
                (
                    "taakr_basis_url",
                    models.URLField(default="http://taakr.mor.local:8009"),
                ),
                (
                    "onderwerpen_basis_url",
                    models.URLField(default="http://onderwerpen.mor.local:8006"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
