# Generated by Django 4.2.15 on 2025-10-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instellingen", "0002_instelling_email_beheer"),
    ]

    operations = [
        migrations.AddField(
            model_name="instelling",
            name="locaties_basis_url",
            field=models.URLField(default="http://locaties.mor.local:8010"),
        ),
    ]
