# Generated by Django 3.2.16 on 2023-11-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticatie", "0003_gebruiker_telefoonnummer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gebruiker",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="E-mailadres"
            ),
        ),
    ]
