# Generated by Django 3.2.16 on 2024-02-27 15:31

import uuid

import django.db.models.deletion
import utils.images
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("titel", models.CharField(max_length=255)),
                ("beschrijving", models.TextField(blank=True, max_length=1000)),
                ("publicatie_datum", models.DateTimeField()),
                ("versie", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "bekeken_door_gebruikers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bekeken_release_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bijlage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "bestand",
                    models.FileField(
                        max_length=255, upload_to=utils.images.get_upload_path
                    ),
                ),
                (
                    "afbeelding",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=utils.images.get_upload_path,
                    ),
                ),
                (
                    "afbeelding_verkleind",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=utils.images.get_upload_path,
                    ),
                ),
                ("mimetype", models.CharField(max_length=30)),
                ("is_afbeelding", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bijlage",
                "verbose_name_plural": "Bijlagen",
            },
        ),
    ]
