# Generated by Django 3.2.16 on 2024-09-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("release_notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasenote",
            name="beschrijving",
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
