# Generated by Django 4.2.15 on 2024-11-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("release_notes", "0003_releasenote_bericht_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasenote",
            name="link_titel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="releasenote",
            name="link_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
