# Generated by Django 3.2.16 on 2023-09-05 14:29

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("context", "0002_context_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="kolommen",
            field=utils.fields.DictJSONField(default=dict),
        ),
        migrations.AddField(
            model_name="context",
            name="standaard_filters",
            field=utils.fields.DictJSONField(default=dict),
        ),
    ]
