# Generated by Django 3.2.16 on 2023-09-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0003_auto_20230905_1629"),
    ]

    operations = [
        migrations.AlterField(
            model_name="context",
            name="naam",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
