# Generated by Django 3.2.16 on 2023-12-12 10:07

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("context", "0004_alter_context_naam"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="taaktypes",
            field=utils.fields.ListJSONField(default=list),
        ),
    ]
