# Generated by Django 4.2.15 on 2024-11-04 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("context", "0005_context_taaktypes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="context",
            options={
                "ordering": ["naam"],
                "verbose_name": "Rol",
                "verbose_name_plural": "Rollen",
            },
        ),
    ]
