VERTALINGEN = {
    "status_wijziging": "Status wijziging",
    "melding_aangemaakt": "Melding aangemaakt",
    "taakopdracht_aangemaakt": "Taakopdracht aangemaakt",
    "taakopdracht_status_wijziging": "Taakopdracht status wijziging",
    "opgelost": "Opgelost",
    "niet_opgelost": "Niet opgelost",
    "niet_gevonden": "Niets aangetroffen",
    "aangemaakt": "Aangemaakt",
    "gewijzigd": "Gewijzigd",
    "verwijderd": "Verwijderd",
    "in_behandeling": "In uitvoering",
    "openstaand": "Openstaand",
    "controle": "Te controleren",
    "afgehandeld": "Afgehandeld",
    "geannuleerd": "Geannuleerd",
    "nieuw": "Nieuw",
    "bezig": "Bezig",
    "voltooid": "Voltooid",
    "voltooid_met_feedback": "Voltooid met feedback",
    "toegewezen": "Toegewezen",
    "adres": "Ter hoogte van",
    "lichtmast": "Lichtmast",
    "graf": "Graf",
    "vak": "Vak",
    "fotos": "Foto's",
    "aannemer": "Aangenomen door",
    "no_email": "De melder beschikt niet over een e-mailadres.",
    "grafnummer": "Grafnummer",
    "naam_melder": "Naam",
    "toelichting": "Toelichting",
    "email_melder": "E-mailadres",
    "begraafplaats": "Begraafplaats",
    "rechthebbende": "Is deze persoon de rechthebbende of belanghebbende?",
    "specifiek_graf": "Betreft het verzoek een specifiek graf?",
    "naam_overledene": "Naam overledene",
    "telefoon_melder": "Telefoonnummer",
    "terugkoppeling_gewenst": "Is terugkoppeling gewenst?",
    "wachten_melder": "Wachten melder",
    "pauze": "Pauze",
    "standaard": "Opmerking/foto toegevoegd",
    "signaal_toegevoegd": "Samengevoegd",
    "urgentie_aangepast": "Spoed aangepast",
    "melding_heropend": "Heropend",
}

DAGEN_VAN_DE_WEEK_KORT = [
    "ma",
    "di",
    "wo",
    "do",
    "vr",
    "za",
    "zo",
]

MAANDEN = [
    "januari",
    "februari",
    "maart",
    "april",
    "mei",
    "juni",
    "juli",
    "augustus",
    "september",
    "oktober",
    "november",
    "december",
]

MAANDEN_KORT = [
    "jan",
    "feb",
    "mrt",
    "apr",
    "mei",
    "jun",
    "jul",
    "aug",
    "sep",
    "okt",
    "nov",
    "dec",
]

PDOK_WIJKEN = [
    # Noord
    {"wijkcode": "WK059903", "wijknaam": "Delfshaven", "stadsdeel": "Noord"},
    {
        "wijkcode": "WK059906",
        "wijknaam": "Hillegersberg-Schiebroek",
        "stadsdeel": "Noord",
    },
    {"wijkcode": "WK059908", "wijknaam": "Kralingen-Crooswijk", "stadsdeel": "Noord"},
    {"wijkcode": "WK059905", "wijknaam": "Noord", "stadsdeel": "Noord"},
    {"wijkcode": "WK059919", "wijknaam": "Nieuw-Mathenesse", "stadsdeel": "Noord"},
    {"wijkcode": "WK059904", "wijknaam": "Overschie", "stadsdeel": "Noord"},
    {"wijkcode": "WK059925", "wijknaam": "Rivium", "stadsdeel": "Noord"},
    {"wijkcode": "WK059901", "wijknaam": "Rotterdam Centrum", "stadsdeel": "Noord"},
    {"wijkcode": "WK059924", "wijknaam": "Rotterdam-Noord-West", "stadsdeel": "Noord"},
    {"wijkcode": "WK059914", "wijknaam": "Prins Alexander", "stadsdeel": "Noord"},
    {"wijkcode": "WK059918", "wijknaam": "Spaanse Polder", "stadsdeel": "Noord"},
    # Zuid
    {
        "wijkcode": "WK059923",
        "wijknaam": "Botlek-Europoort-Maasvlakte",
        "stadsdeel": "Zuid",
    },
    {"wijkcode": "WK059915", "wijknaam": "Charlois", "stadsdeel": "Zuid"},
    {"wijkcode": "WK059910", "wijknaam": "Feijenoord", "stadsdeel": "Zuid"},
    {"wijkcode": "WK059917", "wijknaam": "Hoek van Holland", "stadsdeel": "Zuid"},
    {"wijkcode": "WK059916", "wijknaam": "Hoogvliet", "stadsdeel": "Zuid"},
    {"wijkcode": "WK059912", "wijknaam": "IJsselmonde", "stadsdeel": "Zuid"},
    {"wijkcode": "WK059913", "wijknaam": "Pernis", "stadsdeel": "Zuid"},
    {"wijkcode": "WK059927", "wijknaam": "Rozenburg", "stadsdeel": "Zuid"},
    {"wijkcode": "WK059922", "wijknaam": "Vondelingenplaat", "stadsdeel": "Zuid"},
    {"wijkcode": "WK059921", "wijknaam": "Waalhaven-Eemhaven", "stadsdeel": "Zuid"},
]

BEGRAAFPLAATSEN = (
    ("1", "Begraafplaats Crooswijk"),
    ("2", "Begraafplaats Hoek van Holland"),
    ("3", "Begraafplaats en crematorium Hofwijk"),
    ("4", "Begraafplaats Oudeland, Hoogvliet"),
    ("5", "Begraafplaats Oud-Hoogvliet"),
    ("6", "Begraafplaats Oud-Overschie"),
    ("7", "Begraafplaats Oud-Pernis"),
    ("8", "Begraafplaats Oud-Schiebroek"),
    ("9", "Begraafplaats Pernis"),
    ("10", "Begraafplaats Rozenburg"),
    ("11", "Zuiderbegraafplaats"),
)

BEGRAAFPLAATSEN_LOOKUP = {
    begraafplaats[0]: begraafplaats[1] for begraafplaats in BEGRAAFPLAATSEN
}
