# Generated by Django 4.2.15 on 2024-10-12 10:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Databron",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                (
                    "brontype",
                    models.CharField(
                        choices=[
                            (
                                "doorlooptijden_afgehandelde_meldingen",
                                "Doorlooptijden afgehandelde meldingen",
                            ),
                            (
                                "status_verandering_duur_meldingen",
                                "Status verandering duur voor meldingen",
                            ),
                            ("nieuwe_melding_aantallen", "Nieuwe melding aantallen"),
                            ("nieuwe_signaal_aantallen", "Nieuwe signaal aantallen"),
                            ("nieuwe_taakopdrachten", "Nieuwe taakopdrachten"),
                            (
                                "taaktype_aantallen_per_melding",
                                "Taaktype aantallen per melding",
                            ),
                            (
                                "taakopdracht_doorlooptijden",
                                "Taakopdracht_doorlooptijden",
                            ),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("url", models.URLField(unique=True)),
                (
                    "start_datumtijd_param",
                    models.CharField(default="aangemaakt_op_gte", max_length=50),
                ),
                (
                    "eind_datumtijd_param",
                    models.CharField(default="aangemaakt_op_lt", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Databron",
                "verbose_name_plural": "Databronnen",
            },
        ),
        migrations.CreateModel(
            name="Tijdsvak",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("start_datumtijd", models.DateTimeField()),
                ("eind_datumtijd", models.DateTimeField()),
                ("valide_data", models.BooleanField(default=False)),
                ("resultaat", models.JSONField(default=list)),
                (
                    "periode",
                    models.CharField(
                        choices=[("dag", "Dag"), ("week", "Week"), ("maan", "Maand")],
                        default="dag",
                        max_length=50,
                    ),
                ),
                (
                    "databron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tijdsvakken_voor_databron",
                        to="dashboard.databron",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tijdsvak",
                "verbose_name_plural": "Tijdsvakken",
                "unique_together": {("databron", "start_datumtijd", "eind_datumtijd")},
            },
        ),
        migrations.CreateModel(
            name="DoorlooptijdenAfgehandeldeMeldingen",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("dashboard.tijdsvak",),
        ),
    ]
